### ISSUE TITLE
Crash on Android 

### ISSUE THREAD

**Issue by matteoKuama** [appspector/flutter-plugin#52]
Hi, I have some weird crash on Android.
I initially tested on my Flutter app, then I tested on the default example Flutter app .
This is the output is the same for both apps. 

When I launch the app: 
```
E/flutter (11976): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (11976): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:121:86)
E/flutter (11976): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:146:36)
E/flutter (11976): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (11976): #3      AppSpectorPlugin.isStarted (package:appspector/src/appspector_plugin.dart:138:16)
E/flutter (11976): #4      AppSpectorPlugin.run (package:appspector/src/appspector_plugin.dart:114:44)
E/flutter (11976): #5      runAppSpector (package:appspectorproject/main.dart:17:20)
E/flutter (11976): #6      main (package:appspectorproject/main.dart:5:3)
E/flutter (11976): #7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:145:25)
E/flutter (11976): #8      _rootRun (dart:async/zone.dart:1428:13)
E/flutter (11976): #9      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (11976): #10     _runZoned (dart:async/zone.dart:1863:10)
E/flutter (11976): #11     runZonedGuarded (dart:async/zone.dart:1851:12)
E/flutter (11976): #12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:141:5)
E/flutter (11976): #13     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter (11976): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Side notes**
I am registered on AppSpector.
I created two projects (iOS and Android) in it.
My Flutter version: 2.5.1 
My Dart SDK version: 2.14.2

I followed the instructions that I found on pub.dev for your plugin so:

- added the dependency on pubspec.yaml
```dependencies
  appspector: '0.8.1'
```
- initialized the plugin in main.dart
```void main() {
  runAppSpector();
  runApp(const MyApp());
}

void runAppSpector() {
  final config = Config()
    ..iosApiKey = "my API key for ios"
    ..androidApiKey = "my API key for android ";
  
  config.monitors = [Monitors.http, Monitors.logs, Monitors.screenshot];

  AppSpectorPlugin.run(config);
}
```

Can you help?
Thanks a lot!

**Comment by Dimdron** [comment]
Thanks for report. We will take a look at this wired behavior

**Comment by Dimdron** [comment]
Hey @matteoKuama, sorry for the delay! I've completely forgotten to answer.
It seems you have not put the `WidgetsFlutterBinding.ensureInitialized();` line before initializing the plugin.
